
#ifndef UNIXSOCKET_PROTO_H
#define UNIXSOCKET_PROTO_H

#define UNIXSOCKET_PROTO_VERSION 0x1

enum {
	UNIXSOCKET_PROTO_DATA = 0x0,
	UNIXSOCKET_PROTO_CONTROL = 0x1,
};

#endif /* UNIXSOCKET_PROTO_H */
